### ISSUE TITLE
init-Methode in feuser Model ist fehlerhaft

### ISSUE THREAD

**Issue by digedag** [digedag/t3users#10]
Folgende Exception wird derzeit in TYPO3 7.6 geworfen:
```php
array (
  'Exception' => 
  array (
    'message' => 'PHP Warning: Declaration of tx_t3users_models_feuser::init($rowOrUid, $bEnableFieldsOff = false) should be compatible with tx_rnbase_model_base::init($rowOrUid = NULL) in /usr/www/typo3/typo3conf/ext/t3users/models/class.tx_t3users_models_feuser.php line 32',
    'code' => 1,
    'file' => '/usr/www/typo3_src-7.6.18/typo3/sysext/core/Classes/Error/ErrorHandler.php',
    'line' => 111,
    'trace' => '#0 /usr/www/typo3/typo3conf/ext/t3users/models/class.tx_t3users_models_feuser.php(32): TYPO3\\CMS\\Core\\Error\\ErrorHandler->handleError(2, \'Declaration of ...\', \'/usr/www/users/...\', 32, Array)
#1 /usr/www/typo3_src-7.6.18/vendor/composer/ClassLoader.php(409): include(\'/usr/www/users/...\')
```

**Comment by rengaw83** [comment]
warum gibt es zwei remotes für t3users?
das ist ein php7 problem und wurde in https://github.com/DMKEBUSINESSGMBH/typo3-t3users/issues/3 bereits korrigiert.

**Comment by digedag** [comment]
Gegenfrage: Warum gibt es das andere Repo immer noch??
